apiVersion: v1
kind: ReplicationController
metadata:
  name: damou
  labels:
    run: damou
spec:
  replicas: 1
  selector:
    run: damou
  template:
    metadata:
      labels:
        run: damou
    spec:
      containers:
        - name: damou
          image: damou/node:kubernetes-chapter02
          ports:
            - containerPort: 8080
              protocol: TCP